name: CI for Module OpenId Connect for Scala.
run-name: Testing.

on: [ push, pull_request ]

jobs:
  run-sbt-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: sbt
      - run: sbt coverage +Test/compile +test +it/test +coverageReport +coverageAggregate
