name: CI for Module OpenId Connect for Scala.
run-name: ${{ github.actor }} is running this Github Action.

on: [ push, pull_request ]

jobs:
  run-sbt-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          distribution: temurin
          java-version: 17
          cache: sbt
      - name: Application testing
        run: sbt +test
